spring:
  services:
    user-service:
      url: http://104.128.137.40/api/v1/users
    card-service:
      url: http://26.125.164.47:8085/api/v2/cards
    transfer-service:
      url: http://26.122.215.84:8083/api/v1/transfers
    document-service:
      url: http://185.221.160.131/api/documents
    user-restriction-service:
      url: http://104.128.137.51/api/v1/restrictions