spring:
  services:
    user-service:
      url: ${USER_SERVICE_URL:http://localhost:8081}
    card-service:
      url: ${CARD_SERVICE_URL:http://localhost:8082}
    transfer-service:
      url: ${TRANSFER_SERVICE_URL:http://localhost:8083}
    document-service:
      url: ${DOCUMENT_SERVICE_URL:http://localhost:8084}
    user-restriction-service:
      url: ${USER_RESTRICTION_SERVICE_URL:http://localhost:8085}